<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Validator\**" />
    <EmbeddedResource Remove="Validator\**" />
    <None Remove="Validator\**" />
  </ItemGroup>

</Project>
